variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test
  - deploy

test:
  stage: test
  script: "mvn test"

deploy:
  stage: deploy
  script:
    - export VALIT_DB_LOGIN=$VALIT_DB_LOGIN
    - mvn clean install
    - mv target/valit-backend.jar /db/valit-backend/feedback-backend/target/valit-backend.jar
    - systemctl restart valit-backend.service
    #only:
        #- main

