spring:
  profiles:
    active: local
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/study_feedback?stringtype=unspecified
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
valit:
  app:
    jwtSecret: g4PtQBzI5tN0c8bpD2xu
    jwtExpirationMs: 86400000
