spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/valit_db?stringtype=unspecified
    username: db_username
    password: db_password
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
valit:
  app:
    jwtSecret: valit_jwt_secret
    jwtExpirationDays: 30
    files:
      directory: /db/file-storage
    shortCodeLength: 5
    evaluationCreationOffsetMins: 10

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/study_feedback?stringtype=unspecified
    username: postgres
    password: postgres
